### ISSUE TITLE
Expose SynchronousCursor

### ISSUE THREAD

**Issue by zodern** [lamhieu-vk/meteorx#2]
> SynchronousCursor is a wrapper around a MongoDB cursor
which includes fully-synchronous versions of forEach, etc.

> Cursor is the cursor object returned from find(), which implements the
documented Mongo.Collection cursor API.  It wraps a CursorDescription and a
SynchronousCursor (lazily: it doesn't contact Mongo until you call a method
like fetch or forEach on it).

From https://github.com/meteor/meteor/blob/3051150f2f5ae953f391802e73682fba613b3d46/packages/mongo/mongo_driver.js#L831

One way to expose it is https://github.com/monti-apm/monti-apm-agent/pull/12/commits/995746e638df5806e74d1a94b32bda4f6f883056#diff-0901de04bfe0541714fd28f066b7d8c9R29

**Comment by lh0x00** [comment]
It's a great ideal, I will add it to this package! Thanks for your suggestion!

**Comment by lh0x00** [comment]
hi @zodern 
I added `SynchronousCursor` to `lamhieu:meteorx`, please update to the new version (2.1.1), to use it.
