### ISSUE TITLE
'meteorhacks:kadira' deps on 'meteorhacks/meteorx'

### ISSUE THREAD

**Issue by crapthings** [lamhieu-vk/meteorx#4]
im trying to upgrade our app to 1.9alpha5

any replacement for self hosting kadira

after install lamhieu:unblock, i still got meteorhacks/meteorx undefined error

**Comment by lh0x00** [comment]
I suggest for you 2 way resolve this problem:
1. Use new package like `meteorhacks:kadira`, you can use at `DEPENDANTS` list [here](https://atmospherejs.com/lamhieu/meteorx). I recommend this way.
2. Use local packages. In your applications:
- Create `packages` folder at the root
- Clone this repo to `packages` folder and go to `meteorx` folder after cloned
- Open `package.js` file and change `name: "lamhieu:meteorx"` to `name: "meteorhacks/meteorx"`
- Re-install your application.

**Comment by lh0x00** [comment]
If the problem was resolved, I'd close this issue!
